### PR TITLE
RES-443 Milestone 2

### PR DESCRIPTION
**Pull request by oxtopus**
Requires companion PR in numenta/nupic.research at https://github.com/numenta/nupic.research/pull/732

This implements changes in pursuit of Milestone 2 in the  "Research & C++ Plan" internal document and marks a dramatic departure from the status quo in which `nupic.research.core` supercedes `nupic.core`.  Instead, `nupic.research.core` complements `nupic.core`.

Major changes include:

- As documented in "Research & C++ Plan" internal document, build only experimental bindings, allowing for installation alongside `nupic.bindings`
- Define new package.  In this case, `htmresearch-core` package name, `htmresearch_core` namespace.
- Users need to have `nupic.core` and `nupic.bindings` installed before running this.
- References to `nupic.bindings.experimental` change to `htmresearch_core.experimental`

Moving forward, you **must** install `nupic.bindings` from https://github.com/numenta/nupic.core. AND install `htmresearch_core`.  The build is mostly the same as w/ `nupic.core` and `nupic.bindings`, with one minor difference (note the value for `-DPY_EXTENSIONS_DIR` to account for difference in directory structure from `nupic.bindings`):

```
cmake ../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../release -DPY_EXTENSIONS_DIR=/Users/amarshall/nta/nupic.research.core/bindings/py/htmresearch_core && make -j6 install
```

### CODE REVIEW

**Comment by subutai** [comment]
Not sure how to review this online - need to discuss plan and review in person. Please don't merge until that

**Comment by oxtopus** [comment]
Yes, of course.  We should not merge this until we understand (and accept) the implications.

**Comment by subutai** [comment]
Do we have corresponding nupic.research PR that must be merged in parallel?

**Comment by oxtopus** [comment]
Yes, at https://github.com/numenta/nupic.research/pull/732 also be sure to review the "Research & C++ Plan" document.

**Comment by subutai** [comment]
Thanks

**Comment by oxtopus** [comment]
See also build pipeline at https://ci.numenta.com/browse/RES-HTMRES in which the official nupic.bindings wheel gets installed, this is tested, and separate installable `htmresearch_core` artifact is generated.

**Comment by oxtopus** [comment]
Here's what I'm using to set up my env for testing:

```bash
#!/usr/bin/env sh

# Build and install nupic.core, nupic.bindings
pushd ${HOME}/nta/nupic.core
mkdir -p build/scripts
pushd build/scripts
cmake ../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../release -DPY_EXTENSIONS_DIR=${HOME}/nta/nupic.core/bindings/py/nupic/bindings
make -j6 install
popd
pushd bindings/py
ARCHFLAGS="-arch x86_64" python setup.py develop --user
popd

# Build and install nupic.bindings
pushd ${HOME}/nta/nupic
python setup.py develop --user
popd

# Build and install htmresearch-core
pushd ${HOME}/nta/nupic.research.core
mkdir -p build/scripts
pushd build/scripts
cmake ../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../release -DPY_EXTENSIONS_DIR=${HOME}/nta/nupic.research.core/bindings/py/htmresearch_core
make -j6 install
popd
pushd bindings/py
python setup.py develop --user
popd

# Build and install htmresearch
pushd ${HOME}/nta/nupic.research
python setup.py develop --user
popd

# Debug
pip freeze | grep -E "(htmresearch|nupic)"
python -c "from pkg_resources import get_distribution; print '\n'.join(': '.join((name, get_distribution(name).version)) for name in ('nupic','nupic.bindings', 'htmresearch', 'htmresearch-core'))"

```

**Comment by oxtopus** [comment]
eh, yeah.  I will add that, fix the title and merge.

**Comment by scottpurdy** [comment]
Don't merge quite yet. Let me know when it's ready.

**Comment by subutai** [comment]
Great!  Could someone test it before merging?

**Comment by scottpurdy** [comment]
@oxtopus - Let's do it!

**Pull request merged**
